import { Incident, ApiTrafficEvent, DetectionRuleItem, ScheduleEvent } from '../types/sentinel';

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'INC-001',
    type: 'BRUTE_FORCE',
    title: 'Excessive Login Failures (Brute-Force)',
    riskScore: 85,
    severity: 'CRITICAL',
    sourceIp: '192.168.1.105',
    endpoint: '/api/demo/login',
    method: 'POST',
    description: 'Detected 7 failed authentication attempts (401 Unauthorized) within 42 seconds from identical source IP.',
    detectionRule: 'Excessive Failed Login Attempts (Threshold: 5 / 60s)',
    status: 'OPEN',
    createdAt: '2 mins ago',
    updatedAt: 'Just now',
    requestCount: 7,
    samplePayload: '{"username": "admin", "password": "wrong_attempt_7"}',
    factors: [
      { factor: 'Brute-force velocity behavior', points: 50 },
      { factor: 'High failure rate (100% 401s)', points: 20 },
      { factor: 'Repeated burst request cadence', points: 15 },
    ],
  },
  {
    id: 'INC-002',
    type: 'SQL_INJECTION_PATTERN',
    title: 'SQL Injection-Like Input Pattern',
    riskScore: 75,
    severity: 'HIGH',
    sourceIp: '10.0.4.12',
    endpoint: '/api/demo/products',
    method: 'GET',
    description: 'Suspicious tautology query parameter detected matching known SQL injection syntax in request query: ?search=\' OR \'1\'=\'1',
    detectionRule: 'Malicious SQL Payload Pattern Matcher',
    status: 'INVESTIGATING',
    createdAt: '18 mins ago',
    updatedAt: '12 mins ago',
    requestCount: 3,
    samplePayload: "GET /api/demo/products?category=electronics&search=%27%20OR%20%271%27=%271",
    factors: [
      { factor: 'Suspicious SQL-like pattern in query string', points: 30 },
      { factor: 'Signature match: Boolean Tautology (OR 1=1)', points: 30 },
      { factor: 'Unauthenticated public probe', points: 15 },
    ],
  },
  {
    id: 'INC-003',
    type: 'API_ABUSE',
    title: 'API Rate Flooding / Excessive Volume',
    riskScore: 65,
    severity: 'HIGH',
    sourceIp: '172.16.0.44',
    endpoint: '/api/demo/orders',
    method: 'GET',
    description: 'Client sent 142 requests in 38 seconds, exceeding the 100 requests / 60s abuse threshold without authorization token.',
    detectionRule: 'Abnormal API Request Frequency Rule',
    status: 'OPEN',
    createdAt: '45 mins ago',
    updatedAt: '40 mins ago',
    requestCount: 142,
    samplePayload: 'GET /api/demo/orders/latest (Burst repeated 142x)',
    factors: [
      { factor: 'Exceeded burst velocity limit (>100 req/min)', points: 35 },
      { factor: 'Automated script signature (headless user agent)', points: 15 },
      { factor: 'Resource exhaustion indicator', points: 15 },
    ],
  },
  {
    id: 'INC-004',
    type: 'SQL_INJECTION_PATTERN',
    title: 'UNION SELECT Extraction Pattern Probe',
    riskScore: 40,
    severity: 'MEDIUM',
    sourceIp: '198.51.100.89',
    endpoint: '/api/demo/users/4',
    method: 'GET',
    description: 'Pattern matching "UNION SELECT" detected in URL path parameters. Flagged for analyst investigation.',
    detectionRule: 'Malicious SQL Payload Pattern Matcher',
    status: 'RESOLVED',
    createdAt: '2 hours ago',
    updatedAt: '1 hour ago',
    requestCount: 1,
    samplePayload: 'GET /api/demo/users/4%20UNION%20SELECT%20null,username,password',
    factors: [
      { factor: 'Suspicious SQL keyword combination (UNION SELECT)', points: 30 },
      { factor: 'Single isolated probe', points: 10 },
    ],
  },
];

export const INITIAL_RULES: DetectionRuleItem[] = [
  {
    id: 'RULE-01',
    name: 'Brute Force Detection',
    type: 'BRUTE_FORCE',
    description: 'Flags source IP when > 5 failed login attempts (401) occur within 60 seconds.',
    threshold: 5,
    timeWindow: 60,
    enabled: true,
  },
  {
    id: 'RULE-02',
    name: 'Excessive API Usage / API Abuse',
    type: 'API_ABUSE',
    description: 'Flags client when > 100 HTTP requests are recorded from same IP within 60 seconds.',
    threshold: 100,
    timeWindow: 60,
    enabled: true,
  },
  {
    id: 'RULE-03',
    name: 'SQL Injection-Like Pattern Detection',
    type: 'SQL_INJECTION_PATTERN',
    description: 'Inspects query parameters and JSON payloads for SQLi signatures (e.g. \' OR \'1\'=\'1, UNION SELECT, DROP TABLE).',
    threshold: 1,
    timeWindow: 10,
    enabled: true,
  },
  {
    id: 'RULE-04',
    name: 'Heuristic Proxy Anomaly Isolation',
    type: 'API_ABUSE',
    description: 'Identifies spoofed User-Agent strings and mismatched X-Forwarded-For headers.',
    threshold: 10,
    timeWindow: 120,
    enabled: false,
  },
];

export const RECENT_TRAFFIC: ApiTrafficEvent[] = [
  {
    id: 'EVT-904',
    timestamp: '11:42:01',
    method: 'POST',
    endpoint: '/api/demo/login',
    statusCode: 401,
    responseTime: 38,
    requestSize: 248,
    responseSize: 92,
    sourceIp: '192.168.1.105',
    userAgent: 'PostmanRuntime/7.39.0',
    riskFlag: true,
    riskType: 'BRUTE_FORCE',
  },
  {
    id: 'EVT-903',
    timestamp: '11:41:58',
    method: 'POST',
    endpoint: '/api/demo/login',
    statusCode: 401,
    responseTime: 41,
    requestSize: 250,
    responseSize: 92,
    sourceIp: '192.168.1.105',
    userAgent: 'PostmanRuntime/7.39.0',
    riskFlag: true,
    riskType: 'BRUTE_FORCE',
  },
  {
    id: 'EVT-902',
    timestamp: '11:41:35',
    method: 'GET',
    endpoint: "/api/demo/products?search=' OR '1'='1",
    statusCode: 200,
    responseTime: 26,
    requestSize: 184,
    responseSize: 1420,
    sourceIp: '10.0.4.12',
    userAgent: 'curl/8.4.0',
    riskFlag: true,
    riskType: 'SQL_INJECTION_PATTERN',
  },
  {
    id: 'EVT-901',
    timestamp: '11:40:55',
    method: 'GET',
    endpoint: '/api/demo/products',
    statusCode: 200,
    responseTime: 22,
    requestSize: 96,
    responseSize: 3410,
    sourceIp: '127.0.0.1',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64)',
    riskFlag: false,
  },
  {
    id: 'EVT-900',
    timestamp: '11:40:12',
    method: 'POST',
    endpoint: '/api/demo/orders',
    statusCode: 201,
    responseTime: 64,
    requestSize: 412,
    responseSize: 310,
    sourceIp: '192.168.1.44',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X)',
    riskFlag: false,
  },
  {
    id: 'EVT-899',
    timestamp: '11:39:48',
    method: 'GET',
    endpoint: '/api/demo/users/12',
    statusCode: 200,
    responseTime: 19,
    requestSize: 112,
    responseSize: 580,
    sourceIp: '127.0.0.1',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0)',
    riskFlag: false,
  },
];

export const SCHEDULE_ITEMS: ScheduleEvent[] = [
  { day: 'Mon', time: '09:00', title: 'Rule Base Calibration', category: 'Security' },
  { day: 'Wed', time: '14:30', title: 'Postman Stress & Attack Run', category: 'Testing' },
  { day: 'Fri', time: '17:00', title: 'Intrusion Report Export', category: 'Audit' },
  { day: 'Sun', time: '02:00', title: 'Automated Log Retention Cycle', category: 'System' },
];

export const WEEKLY_CHART_DATA = [
  { day: 'Mon', requests: 18400, threats: 120, heightPct: 48 },
  { day: 'Tue', requests: 22100, threats: 240, heightPct: 62 },
  { day: 'Wed', requests: 24900, threats: 310, heightPct: 74 },
  { day: 'Thu', requests: 28420, threats: 580, heightPct: 92, active: true },
  { day: 'Fri', requests: 21300, threats: 190, heightPct: 58 },
  { day: 'Sat', requests: 14200, threats: 85, heightPct: 36 },
  { day: 'Sun', requests: 12600, threats: 62, heightPct: 30 },
];
